# the keywords defined in the following lists should be added to the list 'clear' keywords instead of the 'broad' list.
# todo: this is a dirty hack!

int_treaties_broad_to_clear = {}

int_treaties_broad_to_clear['it'] = [
    'accordi italo-svizzeri',
    'accordi italo-svizzero',
    'accordo aels',
    'accordo di doppia imposizione',
    "accordo fra la svizzera e l'italia",
    'accordo italo-svizzero',
    'accordo tra il governo svizzero e quello',
    'accordo tra la cee e la repubblica',
    'accordo tra la confederazione svizzera e la',
    "accordo tra la svizzera e l'italia",
    'convenzione con la francia',
    'convenzione delle nazioni',
    'convenzione di bruxelles',
    'convenzione di doppia imposizione',
    'convenzione di estradizione',
    'convenzione di ginevra',
    'convenzione di lugano',
    'convenzione di vienna',
    'convenzione doganale',
    'convenzione franco-svizzera',
    'convenzione italo-svizzera',
    'convenzione italosvizzera',
    'convenzione sulla sicurezza',
    "convenzione tra l'italia",
    'convenzione tra la confederazione svizzera e la',
    "convenzione tra la svizzera e l'italia",
    'convenzione tra la svizzera e la francia',
    'convenzione tra la svizzera e la jugoslavia',
    'convenzioni di bruxelles',
    'convenzioni di sicurezza',
    'patto onu',
    'trattato anglo-belga',
    'trattato austro-svizzero',
    'trattato con gli stati',
    'trattato con la svizzera',
    'trattato di lucerna',
    'trattato franco-svizzero',
    'trattato francoinglese',
    'trattato italo',
    'trattato italo-svizzero',
    "trattato sull'assistenza",
    'trattato svizzera',
    'trattato tra la confederazione svizzera e la',
    'trattato tra la svizzera e il belgio',
    'trattato usa'
]


int_treaties_broad_to_clear['fr'] = [
    "convention entre la confédération suisse et l'espagne",
    'convention entre la confédération suisse et la',
    'convention entre la confédération suisse et le',
    'convention entre la france et la suisse',
    "accord avec l'allemagne",
    "accord avec l'iata",
    "accord avec l'union",
    'accord avec la france',
    'accord avec les etats-unis',
    'accord de double imposition',
    'accord de siège',
    'accord du gatt/omc',
    'accord eee',
    "accord entre la suisse et l'italie",
    'accord franco-suisse',
    'accord gatt/omc',
    'accord italo-suisse',
    'accord omc',
    'accord schengen',
    "accord sur l'eee",
    'accord sur la libre circulation',
    'accord trips',
    'accord ubs',
    'accords de double imposition',
    'accords de dublin',
    'accords de libre échange',
    'accords de siège',
    'accords du gatt',
    'accords du gatt/omc',
    'accords entre la confédération suisse et la',
    'accords gatt/omc',
    'accords omc',
    'accords sur la double imposition',
    'convention aele',
    'convention australo-suisse',
    "convention avec l'allemagne",
    "convention avec l'autriche",
    "convention avec l'espagne",
    "convention avec l'ex-yougoslavie",
    "convention avec l'italie",
    'convention avec la principauté',
    'convention avec la république',
    'convention avec la suisse',
    'convention avec les etats-unis',
    'convention belgo-suisse',
    "convention d'extradition",
    "convention d'exécution",
    "convention d'istanbul",
    "convention d'unidroit",
    "convention d'union",
    "convention d'établissement",
    'convention de berne',
    'convention de bruxelles',
    'convention de double imposition',
    'convention de genève',
    "convention de l'ocde",
    "convention de l'onu",
    "convention de l'unesco",
    'convention de la haye',
    'convention de lugano',
    'convention de luxembourg',
    'convention de montego',
    'convention de new',
    'convention de paris',
    'convention de tokyo',
    'convention de varsovie',
    'convention de vienne',
    'convention des nations',
    'convention des nations-unies',
    "convention entre la confédération suisse et l'espagne",
    'convention entre la confédération suisse et la',
    'convention entre la confédération suisse et le',
    'convention entre la france et la suisse',
    'convention entre la grande-bretagne',
    "convention entre la suisse et l'italie",
    "convention entre la suisse et la belgique",
    'convention entre la suisse et la france',
    'convention entre la suisse et la principauté',
    'convention entre la suisse et la suède',
    'convention entre la suisse et la tchécoslovaquie',
    'convention entre la suisse et le liechtenstein',
    'convention entre le liban et la suisse',
    'convention franco-monégasque',
    'convention franco-suisse',
    'convention francosuisse',
    'convention germano-suisse',
    'convention germanosuisse',
    'convention gréco-suisse',
    'convention hispano-suisse',
    'convention interaméricaine',
    'convention italo-suisse',
    'convention no',
    'convention no141',
    'convention of',
    'convention oit',
    "convention pour l'exécution",
    "convention pour l'unification",
    "convention pour l'établissement",
    'convention pour la protection',
    'convention pour la reconnaissance',
    'convention pour la répression',
    'convention pour la suisse',
    'convention pénale',
    "convention sur l'extradition",
    "convention sur l'exécution",
    "convention sur l'immunité",
    "convention sur l'élimination",
    'convention sur la loi',
    'convention sur la nationalité',
    'convention sur la prévention',
    'convention sur la reconnaissance',
    'convention sur la succession',
    'convention sur la torture',
    'convention sur le brevet',
    'convention sur le bénéfice',
    'convention sur le transfèrement',
    'convention sur les assurances',
    'convention sur les droits',
    'convention sur les missions',
    'convention turco-suisse',
    'conventions avec la suède',
    "conventions d'extradition",
    "conventions d'exécution",
    'conventions de bruxelles',
    'conventions de genève',
    "conventions de l'oit",
    "conventions de l'unesco",
    'conventions de la haye',
    'conventions de vienne',
    'conventions franco-suisse',
    'conventions francosuisses',
    "conventions sur l'enlèvement",
    'conventions sur la double imposition',
    'pacte onu',
    'pactes des nations',
    'traité américano-suisse',
    "traité avec l'autriche-hongrie",
    'traité avec la france',
    'traité avec la pologne',
    'traité avec la turquie',
    'traité avec la yougoslavie',
    'traité avec le brésil',
    'traité avec les etats-unis',
    'traité belgo-néerlandais',
    'traité ce',
    'traité cee',
    "traité d'entraide",
    "traité d'extradition",
    "traité d'investissement",
    "traité d'établissement",
    "traité de bruxelles",
    "traité de l'extradition",
    "traité de l'uruguay",
    'traité de la cee',
    'traité de rome',
    'traité de vienne',
    'traité entre la confédération suisse et les',
    'traité franco-belge',
    'traité franco-suisse',
    'traité francosuisse',
    'traité germano-suisse',
    'traité hispano-suisse',
    'traité italo-suisse',
    "traité sur l'entraide",
    "traité sur l'extradition",
    'traités avec la pologne',
    'traités avec le brésil',
    "traités d'entraide",
    "traités d'extradition",
    "traités d'établissement",
    'traités de manière',
    'traités de protection',
    'traités des droits',
    'traités entre etats et organisations internationales ou',
    'traités franco-belge',
    'traités sur la protection'
]


int_treaties_broad_to_clear['de'] = [
'1/efta-übereinkommen',
'_freizügigkeitsabkommen_',
'_versicherungsabkommen',
'abgeltungssteuerabkommen',
'ablösungsabkommen',
'ablösungsabkommens',
'adoptionsübereinkommen',
'amtshilfeabkommen',
'assoziationsabkommen',
'assoziierungsabkommen',
'auslieferungs- übereinkunft'
'auslieferungs-übereinkommen',
'auslieferungs-übereinkommens',
'auslieferungs-übereinkunft',
'auslieferungsübereinkunft',
'auslieferungsabkommen',
'auslieferungsabkommens',
'auslieferungsübereinkommen',
'auslieferungsübereinkommens',
'basler übereinkommen',
'basler übereinkommens',
'belgien abkommen',
'belgische abkommen',
'belgischen abkommen',
'berner übereinkunft',
'betäubungsmittel-übereinkommen',
'beweisübereinkommens',
'brüsseler abkommen',
'brüsseler übereinkommen',
'brüsseler übereinkommens',
'brüsseler-übereinkommen',
'bürgerrechtspakt',
'cedaw-übereinkommens',
'chicago-übereinkommen',
'chicago-übereinkommens',
'chicagoer übereinkommen',
'chicagoer übereinkommens',
'cybercrime-übereinkommen',
'cybercrime-übereinkommens',
'deutsch-italienischen abkommen',
'deutsch-italienischen abkommens',
'deutsch-schweizerische abkommen',
'deutsch-schweizerischen abkommens',
'deutsch-schweizerischen übereinkommens',
'dienstleistungsabkommen',
'dienstleistungsübereinkommens',
'doppelbesteuerungsabkommen',
'doppelbesteuerungsabkommens',
'dublin-assoziierungsabkommen',
'dublin-assoziierungsabkommens',
'dubliner übereinkommen',
'durchführungsübereinkommen',
'durchführungsübereinkommens'
'efta- übereinkommens',
'efta-abkommen',
'efta-abkommens',
'efta-übereinkommen',
'efta-übereinkommens',
'efta-übereinkommens; abkommen',
'einheits-übereinkommen',
'einheits-übereinkommens',
'einheitsübereinkommens',
'eisenbahnabkommen',
'entführungsübereinkommen',
'entführungsübereinkommens',
'entschädigungsabkommen',
'entschädigungsabkommens',
'europarat-übereinkommen',
'europarats-übereinkommens',
'europaratsübereinkommen',
'ewr-abkommen',
'ewr-abkommens',
'fernsehabkommen',
'flüchtlingsabkommen',
'flüchtlingsabkommens',
'französisch-schweizerischen abkommen',
'französisch-schweizerischen abkommens',
'französisch-spanischen abkommen',
'freihandelsabkommen',
'freihandelsabkommens',
'freizu?gigkeitsabkommen',
'freizügigkeitsabkommen',
'freizügigkeitsabkommens',
'fza/efta-übereinkommen',
'gats-abkommens',
'gatt/wto- übereinkommens',
'gatt/wto-abkommens',
'gatt/wto-übereinkommen',
'gatt/wto-übereinkommens',
'gatt/wto/trips-abkommens',
'gatt/wto/trips-übereinkommens',
'geldwäschereiübereinkommen',
'genfer abkommen',
'genfer abkommens',
'genfer übereinkommen',
'genfer übereinkommens',
'gerichtsstandsabkommens',
'grenzabkommen',
'grenzabkommens',
'haager abkommen',
'haager abkommens',
'haager übereinkommen',
'haager übereinkommens',
'haager übereinkunft',
'handelsabkommen',
'handelsabkommens',
'handelssachen[lugano-übereinkommen',
'handelsübereinkunft',
'iao-übereinkommen',
'iao-übereinkommens',
'investitionsschutzabkommen',
'ipr übereinkommen',
'iprg; übereinkommen',
'italienerabkommen',
'italienerabkommens',
'italienisch-schweizerischen abkommens',
'italienisch-schweizerischen übereinkommens',
'italienische abkommen',
'italienischen abkommens',
'kelloggpakt',
'kinderschutzübereinkommens',
'kindesentführungsübereinkommens',
'kindesschutzübereinkommen',
'kindesschutzübereinkommens',
'kyoto-abkommen',
'kyoto-abkommens',
'kyoto-übereinkommen',
'kyoto-übereinkommens',
'landverkehrsabkommen',
'landverkehrsabkommens',
'leistungspakten',
'lissabonner abkommen',
'lissabonner übereinkommen',
'lissabonner übereinkommens',
'londoner abkommen',
'londoner abkommens',
'luftfahrtabkommen',
'luftverkehrsabkommen',
'luftverkehrsabkommens',
'luganer übereinkommen',
'luganer übereinkommens',
'lugano übereinkommen',
'lugano übereinkommens',
'lugano- übereinkommen',
'lugano-übereinkommen',
'lugano-übereinkommens',
'luganoübereinkommen',
'luzerner-übereinkunft',
'madrider abkommen',
'madrider abkommens',
'madrider übereinkunft',
'markenabkommen',
'markenabkommens',
'minderjährigenschutzabkommen',
'minderjährigenschutzabkommens',
'minsker abkommen',
'montrealer übereinkommens',
'multilaterale übereinkommen',
'multilateralen abkommen',
'neuenburger abkommen',
'neuenburger abkommens',
'new-yorker abkommen',
'niederlassungsabkommen',
'niederlassungsabkommens',
'nizza-abkommen',
'ocde-übereinkommens',
'oecd-musterabkommen',
'oecd-musterabkommens',
'pariser übereinkunft',
'patentharmonisierungsabkommen',
'patentübereinkommen',
'patentübereinkommens',
'personenfreizügigkeitsabkommen',
'personenfreizügigkeitsabkommens',
'personenverkehrsabkommen',
'personenverkehrsabkommens',
'privatrecht/lugano-abkommen',
'rassendiskriminierungs-übereinkommen',
'rassendiskriminierungs-übereinkommens',
'rechtsschutzabkommens',
'rom-abkommen',
'rom-abkommens',
'rücknahmeabkommen',
'rückübernahmeabkommen',
'schengen-assoziierungsabkommen',
'schengen-assoziierungsabkommens',
'schwedischen abkommens',
'schweizerisch-amerikanische abkommen',
'schweizerisch-amerikanischen abkommen',
'schweizerisch-amerikanischendoppelbesteuerungsabkommenvom',
'schweizerisch-amerikanisches abkommen',
'schweizerisch-badischen übereinkunft',
'schweizerisch-belgische abkommen',
'schweizerisch-belgischen abkommens',
'schweizerisch-britischen abkommens',
'schweizerisch-deutsche abkommen',
'schweizerisch-deutschen abkommen',
'schweizerisch-deutschen abkommens',
'schweizerisch-deutschenvollstreckungsabkommens',
'schweizerisch-deutsches abkommen',
'schweizerisch-französische abkommen',
'schweizerisch-französischen abkommens',
'schweizerisch-griechische abkommen',
'schweizerisch-griechischen abkommens',
'schweizerisch-italienische abkommen',
'schweizerisch-italienischen abkommen',
'schweizerisch-italienischen abkommens',
'schweizerisch-italienisches abkommen',
'schweizerisch-jugoslawischen abkommen',
'schweizerisch-jugoslawischen abkommens',
'schweizerisch-liechtensteinische abkommen',
'schweizerisch-norwegische abkommen',
'schweizerisch-spanischen abkommens',
'schweizerisch-spanischen abkommensrecht',
'schweizerisch-tschechoslowakischen abkommens',
'schweizerisch-tschechoslowakisches abkommen',
'schweizerisch-türkischen abkommen',
'schweizerisch-türkischen abkommens',
'schweizerisch-österreichische abkommen',
'schweizerisch-österreichischen abkommen',
'schweizerisch-österreichischen abkommens',
'schweizerisch/französischen übereinkommens',
'schweizerischdeutsche abkommen',
'schweizerischdeutschen abkommens',
'schweizerische-italienische abkommen',
'schweizerischitalienischen abkommen',
'sitzabkommen',
'sitzabkommens',
'sklavereiabkommen',
'sorgerechtsübereinkommen',
'sozialpakt',
'sozialpaktes',
'sozialpakts',
'sozialversicherungsabkommen',
'sozialversicherungsabkommens',
'spanisch-schweizerische abkommen',
'strafrechts-übereinkommen',
'strassburger übereinkommen',
'telekommunikationsabkommens',
'tokioter abkommen',
'tokioter abkommens',
'tonträger-übereinkommen',
'trips-abkommen',
'trips-abkommens',
'trips-übereinkommen',
'trips-übereinkommens',
'tschechoslowakisch-schweizerische abkommen',
'tschechoslowakisch-schweizerischen abkommens',
'türkisch-schweizerische abkommen',
'ubs-abkommen',
'ubs-abkommens',
'ubs-amtshilfeabkommen',
'un-kaufrechtsübereinkommen',
'un-pakt',
'un-übereinkommen',
'un-übereinkommens',
'undfreizügigkeitsabkommen',
'uno pakt',
'uno- pakt',
'uno-menschenrechtspakte',
'uno-menschenrechtsübereinkommen',
'uno-pakt',
'uno-pakte',
'uno-paktes',
'uno-pakts',
'uno-sozialpaktes',
'uno-übereinkommen',
'uno-übereinkommens',
'upov übereinkommen',
'upov übereinkommens',
'urteilsvollstreckungsabkommen',
'urteilsvollstreckungsabkommens',
'verbandsübereinkunft',
'verbandübereinkunft',
'versicherungsabkommen',
'versicherungsabkommens',
'vollstreckungsabkommen',
'vollstreckungsabkommens',
'vollstreckungsübereinkommen',
'vollstreckungsübereinkommens',
'vollziehungsabkommen',
'vollzugsübereinkommen',
'warschau abkommens',
'warschauer abkommen',
'warschauer abkommens',
'washingtoner abkommens',
'weltabkommens',
'weltpakt',
'welturheberrechts-abkommen',
'welturheberrechtsabkommen',
'weltübereinkommens',
'wertpapierübereinkommen',
'wiener übereinkommen',
'wiener übereinkommens',
'wto-abkommen',
'wto-abkommens',
'wto-übereinkommens',
'wto/gats-abkommen',
'wto/gats-abkommens',
'yorker abkommen',
'yorker abkommens',
'yorker übereinkommen',
'yorker übereinkommens',
'zinsbesteuerungsabkommen',
'zustellungsübereinkommen',
'zustellungsübereinkommens',
'österreichisch-schweizerischen abkommen',
'weltpostvertrag',
'zivilprozessrechts-übereinkunft',
'zivilprozessübereinkunft'
]